# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RoGMx6W2Jemzicyakten0MOwBZ5fkTf
"""

!pip install transformers sentencepiece torch -q

from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="google/flan-t5-small"
)

print("Model loaded successfully!")

prompt1 = "What are three ways to save money as a college student?"

result1 = generator(prompt1, max_length=100)

print("Prompt 1:", prompt1)
print("Output:", result1[0]["generated_text"])

prompt2 = "Write a short motivational quote for students during exams."

result2 = generator(prompt2, max_length=60)

print("Prompt 2:", prompt2)
print("Output:", result2[0]["generated_text"])

"""The observations:
- The model didn't respond correctly to all the prompts.
- The sentence formation is also wrong.
- It gave short and relevant answers.
- The model followed instructions such as listing ideas and summarizing.

"""